checks:
  php:
    code_rating: true
    deprecated_code_usage: true
    duplication: true
    no_short_open_tag: true
build:
  cache:
    directories:
      - "vendor"
      - "~/.composer"
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
  dependencies:
    override:
      - COMPOSER_ROOT_VERSION=dev-master
filter:
  excluded_paths:
    - "docs/"
    - "tests/"
  dependency_paths:
    - "vendor/"
tools:
  external_code_coverage: false
  php_analyzer: true
  php_code_sniffer:
    config:
      standard: PSR12
  php_cpd:
    enabled: true
    excluded_dirs: [bin, data, docs, docker, public, tests, vendor]
  php_loc:
    enabled: true
    excluded_dirs: [bin, data, docs, docker, public, tests, vendor]
  php_mess_detector: true
  php_pdepend: true
  sensiolabs_security_checker: true
