<?php
/**
 * @copyright Bluz PHP Team
 * @link https://github.com/bluzphp/framework
 */

/**
 * @namespace
 */
namespace Bluz\Tests\Db;

use Bluz;
use Bluz\Db\Row;
use Bluz\Db\Table;
use Bluz\Tests\Fixtures\Db;
use Bluz\Tests\TestCase;

/**
 * Test class for Row.
 * Generated by PHPUnit on 2011-07-27 at 13:52:01.
 */
class RowTest extends TestCase
{

    /**
     * @var Row
     */
    protected $row;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        $this->row = new Db\ConcreteRow();
    }

    /**
     * @covers Row::__get
     */
    public function testGet()
    {
        self::assertNull($this->row->someValue);
    }

    /**
     * @covers Row::__set
     */
    public function testSet()
    {
        $this->row->someValue = 'foo';
        self::assertEquals('foo', $this->row->someValue);
    }

    /**
     * @todo Implement testIsset().
     */
    public function testIsset()
    {
        // Remove the following lines when you implement this test.
        self::markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @todo Implement testSave().
     */
    public function testSave()
    {
        // Remove the following lines when you implement this test.
        self::markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @todo Implement testDelete().
     */
    public function testDelete()
    {
        // Remove the following lines when you implement this test.
        self::markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @todo Implement testRefresh().
     */
    public function testRefresh()
    {
        // Remove the following lines when you implement this test.
        self::markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @covers Row::getTable
     */
    public function testGetTable()
    {
        $table = $this->row->getTable();
        self::assertTrue($table instanceof Table);
    }

    /**
     * @covers Row::getTable
     * @expectedException Bluz\Db\Exception\TableNotFoundException
     */
    public function testGetTableException()
    {
        $this->row = new Db\ConcreteRowWithInvalidTable();
        $this->row->getTable();
    }
    
    /**
     * @todo Implement testGetRelation().
     */
    public function testGetRelation()
    {
        // Remove the following lines when you implement this test.
        self::markTestIncomplete('This test has not been implemented yet.');
    }
    
    /**
     * @expectedException Bluz\Db\Exception\RelationNotFoundException
     */
    public function testGetRelationException()
    {
        $this->row->getRelation('wrongRelation');
    }

    /**
     * @todo Implement testSetRelation().
     */
    public function testSetRelation()
    {
        // Remove the following lines when you implement this test.
        self::markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @todo Implement testToArray().
     */
    public function testToArray()
    {
        // Remove the following lines when you implement this test.
        self::markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * @todo Implement testSetFromArray().
     */
    public function testSetFromArray()
    {
        // Remove the following lines when you implement this test.
        self::markTestIncomplete('This test has not been implemented yet.');
    }

    /**
     * Test ArrayAccess interface
     *  - offsetSet
     */
    public function testOffsetSet()
    {
        $this->row['someValue'] = 'foo';
        self::assertEquals('foo', $this->row->someValue);
    }

    /**
     * Test ArrayAccess interface
     *  - offsetExists
     */
    public function testOffsetExists()
    {
        $this->row->someValue = 'foo';
        self::assertTrue(isset($this->row['someValue']));
    }

    /**
     * Test ArrayAccess interface
     *  - offsetUnset
     */
    public function testOffsetUnset()
    {
        $this->row->someValue = 'foo';
        unset($this->row['someValue']);
        self::assertFalse(isset($this->row['someValue']));
    }

    /**
     * Test ArrayAccess interface
     *  - offsetGet
     */
    public function testOffsetGet()
    {
        $this->row->someValue = 'foo';
        self::assertEquals('foo', $this->row['someValue']);
    }
}
