<?php
/** @var \Bluz\View\View $this */
/** @var string $message */
/** @var string $description */
/** @var \Exception $exception */
?>
<div class="modal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title"><?= esc($message) ?></h5>
            </div>
            <div class="modal-body">
                <p><?= esc($description) ?></p>
                <?= $this->exception($exception) ?>
            </div>
            <div class="modal-footer">
            </div>
        </div>
    </div>
</div>
